.idea/gradle.xml
app/src/main/java/com/example/rfid_mobilapp/NfcTagUtil.java

Here I am testing a pull request

testing pull request

---

app/src/main/java/com/example/rfid_mobilapp/MainActivity.java
app/src/main/java/com/example/rfid_mobilapp/NfcTagUtil.java

Success to write to the tag and create some private methodes to help

Aml abbas patch 1

---

app/src/main/java/com/example/rfid_mobilapp/NfcTagUtil.java

Changed the methods toByteArray where an array with bytes is returned
Changed method getResult where a byte array is converted to a String.

Return array with bytes + conversion from byte array to String

---

app/src/main/java/com/example/rfid_mobilapp/MainActivity.java
app/src/main/java/com/example/rfid_mobilapp/NfcTagUtil.java

Deleted debugging and comments

Deleted debugging and comments

---

app/src/main/java/com/example/rfid_mobilapp/NfcTagUtil.java

Removed unnecessary methods for returning byteArray and primeItemID. Instead, I have integrated the necessary parts into the code, see below.

Removed unnecessary methods

---

app/src/main/java/com/example/rfid_mobilapp/NfcTagUtil.java

These changes make sure that we take the current data and replace the barcode with our new value.
So we leave data like Country, Owner library, Usage etc alone.
⚠️ Note that there is more work to be done, for example the CRC value would need to be recalculated and set, but is is currently left as is.
⚠️ Also note that this code is barely tested. I can confirm that it replace the barcode but it could potentially make the data invalid on the chip, apart from also making the CRC value invalid.

Early example writing multiple blocks setting barcode

---

app/src/main/java/com/example/rfid_mobilapp/MainActivity.java
app/src/main/java/com/example/rfid_mobilapp/NfcTagUtil.java

We are able now to check in and out, I added two methods getCommand to get the command to write the AFI values.

Success to check in and check out

---

app/src/main/java/com/example/rfid_mobilapp/MainActivity.java
app/src/main/java/com/example/rfid_mobilapp/NfcTagUtil.java
app/src/main/java/com/example/rfid_mobilapp/Utilities.java

created som methods to break out the code in smaller parts

some changes to make the code more usable

---

Quria/index.html
app/src/main/java/com/example/rfid_mobilapp/MainActivity.java
app/src/main/java/com/example/rfid_mobilapp/NfcTagUtil.java

🚫 Do not merge yet please, lets discuss the proposed changes 🙂

Improvement suggestions

---

Quria/index.html
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/rfid_mobilapp/MainActivity.java
app/src/main/java/com/example/rfid_mobilapp/SocketServer.java
app/src/main/java/com/example/rfid_mobilapp/SocketServerService.java

Basic flow (read/write) seems to work, if everything starts.
Still the issue of the service not starting always.

Continued work daniel

---

app/src/main/java/com/example/rfid_mobilapp/MainActivity.java
app/src/main/java/com/example/rfid_mobilapp/NfcActivity.java
app/src/main/java/com/example/rfid_mobilapp/NfcTagUtil.java

first one:
when the tag is null
second one:
when the switch is not set
changed the name of the switch from stopSocketServiceSwitch to socketServiceSwitch
and changed the name of the method from setUpStopSocketServiceButton to setUpSocketServiceButton

Fixed the bugs that were detected and changed the name of switch and a method

---

Quria/index.html
Quria/javaScript.js

div in the html to show the camera
the javascript code to init Qugga and detect arcode

Barcode reader

---

Quria/index.html
Quria/javaScript.js
Quria/style.css

new modal to check out with a button to open te camera stream to read barcode 
new modal to show the camera stream
moved the camera div to the new modal that show the camera

Reading the barcode on the borrow card

---

Quria/index.html
Quria/javaScript.js
Quria/style.css
app/src/main/java/com/example/rfid_mobilapp/MainActivity.java
app/src/main/java/com/example/rfid_mobilapp/NfcTagUtil.java
app/src/main/java/com/example/rfid_mobilapp/SocketServer.java
app/src/main/java/com/example/rfid_mobilapp/SocketServerService.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/values-sv-rSE/strings.xml
app/src/main/res/values/strings.xml

it is ok to start the app many times, click on the switch many times on and off. But when the website is connected it doesn't work. When we close the connection, and want to open it again the server calls onstop(). it is just wait 10 minutes befor starting it again.

some changes before usability test- to fix: the server calls onStop()  

---

app/src/main/java/com/example/rfid_mobilapp/MainActivity.java
app/src/main/java/com/example/rfid_mobilapp/SocketServer.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/values-sv-rSE/strings.xml
app/src/main/res/values/strings.xml

the problem with the server onEroor is solved by waiting one minut befor opening the connection again to be sure that the thread is stopped. Disable the switch clicking to be sure that the user will not click on the button before one minute and show a mgs to tell the user not to open the connection before one minut

added a textview with a msg to tell the user to wait before opening the connection 

---

app/src/main/java/com/example/rfid_mobilapp/NfcActivity.java
app/src/main/res/values-sv-rSE/strings.xml
app/src/main/res/values/strings.xml

Did some minor changes to String values

Minor changes to String values

---

Quria/index.html
Quria/javaScript.js
Quria/style.css
app/src/main/java/com/example/rfid_mobilapp/MainActivity.java
app/src/main/java/com/example/rfid_mobilapp/NfcTagUtil.java
app/src/main/java/com/example/rfid_mobilapp/SocketServerService.java
gradle.properties

changes are:
- responsiv design
- show the itemid only if the book doesn't excist in the books array
- some usability changes after two user's test

some changes after meeting 22april

---

Quria/javaScript.js
Quria/style.css

will accept the pull request to check the camera on the https

design the show patron camera

---

Quria/index.html
Quria/javaScript.js
Quria/style.css
app/src/main/java/com/example/rfid_mobilapp/MainActivity.java
app/src/main/java/com/example/rfid_mobilapp/NfcActivity.java
app/src/main/java/com/example/rfid_mobilapp/SocketServer.java
app/src/main/res/layout/activity_nfc.xml
app/src/main/res/values-sv-rSE/strings.xml
app/src/main/res/values/strings.xml

I added a button in the NfcActivity to take the user to the MainActivity, It is the solution for now. Will accept the pull request after being accepted av Daniel.

add a button to take the user to the UI_activity

---

Quria/javaScript.js
Quria/style.css
app/src/main/java/com/example/rfid_mobilapp/MainActivity.java

add style for modal
check if the server is on befor stopping it

fix some problems which occurs after changes in the old pull request
